language: php

matrix:
  include:
    - php: 5.4
      env: DOCTRINE_ORM_VERSION=2.2.3
    - php: 5.4
      env: DOCTRINE_ORM_VERSION=2.3.*
    - php: 5.4
      env: DOCTRINE_ORM_VERSION=2.4.*
    - php: 5.5
      env:
        - COVERALLS=yes
        - DOCTRINE_ORM_VERSION=2.2.3
    - php: 5.5
      env:
        - COVERALLS=yes
        - DOCTRINE_ORM_VERSION=2.3.*
    - php: 5.5
      env:
        - COVERALLS=yes
        - DOCTRINE_ORM_VERSION=2.4.*

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar require doctrine/orm:${DOCTRINE_ORM_VERSION} --no-update
  - php composer.phar install --prefer-source --dev

script:
  - vendor/bin/phpunit --coverage-text

after_success:
  - vendor/bin/phpcs -v --report=summary --standard=PSR1,PSR2 src/ tests/
  - vendor/bin/phpmd src/,tests/ text codesize,unusedcode,design
  - if [ "$COVERALLS" = "yes" ]; then php composer.phar require --dev satooshi/php-coveralls dev-master && vendor/bin/coveralls -vvv; fi
